name: My First Test Workflow
on: push
jobs:
  deploy:
    name: This is New Job
    runs-on: ubuntu-latest
    steps:
    - name: This is step1
      run : ls -alrt
    - name: OS Details
      shell: bash
      run: | 
        git clone https://github.com/sreddy2809/APR27.git
        ls -l
        docker info 
        mvn -v