name: My First Test Workflow
on: push
jobs:
  deploy:
    name: This is New Job
    runs-on: ubuntu-latest
    steps:
    - name: docker login
      run: |
         docker login -u svreddyaws56 -p Omguru0528#D