name: My First Test Workflow
on: push
jobs:
  deploy:
    name: This is New Job
    runs-on: ubuntu-latest
    steps:
    - name: setup terraform 
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: "1.14.9"
    - name: Check version
      run: |
         terraform --version